#!/bin/sh

# flat water surface in one band
# 4 x 8 directional structure
 
# set the verbosity level to '2' if not specified
if [ -n "$1" ]; then VB=$1; else VB=2; fi

$JUDE2DIR/bin/surftool \
    verbose=$VB \
    band_count=1 \
    partition=sphere \
    vn=4 \
    hn=8 \
    type=flat \
    refrac_index_0=1.33 \
    refrac_index_1=1 \
    sub_quad_count=100000 \
    surface_save_fp=sf_flat_mono_4x8
