#!/bin/sh

# run_real_HL18x24

# set the verbosity level to '2' if not specified
if [ -n "$1" ]; then VB=$1; else VB=2; fi

$JUDE2DIR/bin/slabtool \
    verbose=$VB \
    band_count=17 \
    band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
    partition=sphere \
    vn=18 \
    hn=24 \
    theta_points=0,5,15,25,35,45,55,65,75,85,90,95,105,115,125,135,145,155,165,175,180 \
    depth=1 \
    sample_point_distance=1 \
    sample_point_delta_distance=0.01 \
    sky_fp=sky_clear_z45_a50_17_HL18x24 \
    sky_band_count=17 \
    sky_band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
    water_surface_fp=sf_flat_mono_HL18x24 \
    atten_fp=bz052_c17.txt \
    atten_band_count=17 \
    atten_band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
    scat_fp=bz052_b17.txt \
    scat_band_count=17 \
    scat_band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
    pf_fp=pf_petzold_mono_HL18x24 \
    bottom_reflec_diffuse_fp=ger_sand17.txt \
    bottom_reflec_diffuse_band_count=17 \
    bottom_reflec_diffuse_band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
    Ld_b_image_save_fp=image_Ld_b.ppm \
    Lu_b_image_save_fp=image_Lu_b.ppm \
    Ld_a_image_save_fp=image_Ld_a.ppm \
    Lu_a_image_save_fp=image_Lu_a.ppm \
    Ld_w_image_save_fp=image_Ld_w.ppm \
    Lu_w_image_save_fp=image_Lu_w.ppm \
    Lu_wl_image_save_fp=image_Lu_wl.ppm \
    Ld_b_save_fp=Ld_b_data
 
# band_count=17 \
#    band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
 