#!/bin/sh

# run_petzold_mono_HL18x24 
# Petzold's phase function in one band in HL18x24 directional structure

# set the verbosity level to '2' if not specified
if [ -n "$1" ]; then VB=$1; else VB=2; fi

$JUDE2DIR/bin/phasetool \
    verbose=$VB \
    band_count=1 \
    partition=sphere \
    vn=18 \
    hn=24 \
    theta_points=0,5,15,25,35,45,55,65,75,85,90,95,105,115,125,135,145,155,165,175,180 \
    type=petzold \
    sub_quad_count=10000 \
    phase_func_save_fp=pf_petzold_mono_HL18x24
