
// envvars.h

#ifndef _JUDE_TOOL_ENVVARS_H
#define _JUDE_TOOL_ENVVARS_H


#define ENV_TEMP_DIR "RT_TEMP_DIR"
#define ENV_BANDSPEC_DIR "RT_BANDSPEC_DIR"
#define ENV_DIRECSPEC_DIR "RT_DIRECSPEC_DIR"
#define ENV_FILES_DIR "RT_FILES_DIR"
#define ENV_LIBRADTRAN_DIR "RT_LIBRADTRAN_DIR"



#endif // _JUDE_TOOL_ENVVARS_H

