#!/bin/bash

# run_real_HL18x24

function one_run {

  local INTEG=$1
  local PF=$2
  local SURF=$3
  local SUBS=$4
  local DEPTH=$5


  if [ $INTEG == "basic" ]
  then
    INTEG_TYPE="basic_integrate"
  elif [ $INTEG == "dft" ]
  then
    INTEG_TYPE="integrate"
  fi


  if [ $PF == "petzold" ]
  then
    PF_FILE=pf_petzold_mono_4x8
  elif [ $PF == "forward" ]
  then
    PF_FILE=pf_forward_mono_4x8
  fi


  if [ $SURF == "absent" ]
  then
    SURF_FILE=sf_absent_mono_4x8
  elif [ $SURF == "flat" ]
  then
    SURF_FILE=sf_flat_mono_4x8
  fi


  local OUTDIR="out_"$INTEG"_"$PF"_"$SURF"_"$SUBS"_"$DEPTH"m"

  mkdir -p $OUTDIR

  $JUDE2DIR/bin/slabtool \
    verbose=$VB \
    band_count=1 \
    solution=$INTEG_TYPE \
    integrator=euler \
    partition=sphere \
    vn=4 \
    hn=8 \
    depth=$DEPTH \
    sample_point_distance=$DEPTH \
    sky_fp=sky_spec_z45_a50_mono_4x8 \
    water_surface_fp=$SURF_FILE \
    atten_data=1 \
    scat_data=0.5 \
    pf_fp=$PF_FILE \
    bottom_reflec_diffuse_data=0 \
    Ld_b_image_save_fp=$OUTDIR/image_Ld_b.ppm \
    Ld_b_image_sens_k=1.0 \
    Lu_b_image_save_fp=$OUTDIR/image_Lu_b.ppm \
    Lu_b_image_sens_k=1.0 \
    Ld_a_image_save_fp=$OUTDIR/image_Ld_a.ppm \
    Ld_a_image_sens_k=1.0 \
    Lu_a_image_save_fp=$OUTDIR/image_Lu_a.ppm \
    Lu_a_image_sens_k=5.0 \
    Ld_w_image_save_fp=$OUTDIR/image_Ld_w.ppm \
    Ld_w_image_sens_k=1.0 \
    Lu_w_image_save_fp=$OUTDIR/image_Lu_w.ppm \
    Lu_w_image_sens_k=1.0 \
    Lu_wl_image_save_fp=$OUTDIR/image_Lu_wl.ppm \
    Lu_wl_image_sens_k=5.0

#    Lu_w_save_fp=Lu_w_data \
#    Ld_w_save_fp=Ld_w_data

}


# set the verbosity level to '2' if not specified
if [ -n "$1" ]; then VB=$1; else VB=2; fi

#one_run basic petzold absent black 1
#one_run dft petzold absent black 1

one_run basic petzold flat black 1
one_run dft petzold flat black 1
 


#  euler_steps_per_optical_depth=1 \
 
# band_centres_data=510 \
   
#     bottom_reflec_diffuse_data=0.3 \

#    sky_band_count=17 \
#    sky_band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \

 #  scat_fp=bz052_b17.txt \
 #   scat_band_count=17 \
 #   scat_band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
 
#  bottom_reflec_diffuse_fp=ger_sand17.txt \
#    bottom_reflec_diffuse_band_count=17 \
#    bottom_reflec_diffuse_band_centres_data=410,430,450,470,490,510,530,550,570,590,610,630,650,670,690,710,730 \
   

#    Ed_b_save_fp=out_Ed_b_cm1.txt \
#    Ld_b_save_fp=out_Ld_b_cm1 \
